spring:
  application:
    name: ms-iam

  # ================================= #
  #      Security Configuration       #
  # ================================= #
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8091/realms/ttm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  # ================================= #
  # Cloud Configuration               #
  # ================================= #
  cloud:
    config:
      enabled: false

    security:
      enabled=false:

  # ================================= #
  #            RabbitMq               #
  # ================================= #
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # ================================= #
  #     Datasource Configuration      #
  # ================================= #
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ttm-iam-db}
    username: postgres
    password: yassinecoding
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# ================================= #
#       Server Configuration        #
# ================================= #
server:
  port: 8087

# ================================= #
#      Swagger Configuration        #
# ================================= #
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


# ================================================== #
#    Resilience4j (circuit breaker) Configuration    #
# ================================================== #
resilience4j:
  circuitbreaker:
    instances:
      projectServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 5           #  Définit le nombre de requêtes prises en compte pour calculer le taux d'échec.
        failureRateThreshold: 50        # Pourcentage de requêtes échouées pour ouvrir le circuit
        waitDurationInOpenState: 5s     # Temps avant de retester un appel après ouverture du circuit (halfOpen)
        permittedNumberOfCallsInHalfOpenState: 3 # Nombre d'appels permis en mode semi-ouvert
        minimumNumberOfCalls: 5         # Nombre minimal de requêtes avant d'évaluer l'état du circuit



# ================================= #
#       Actuator Configuration      #
# ================================= #

management:
  endpoints:
    web:
      exposure:
        include: "*"        # Enable all actuator endpoints for testing
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true



# ================================= #
#          Keycloak Config          #
# ================================= #
authorization:
  server-url: http://localhost:8091
  client:
    id: ms-iam
    secret: yoursecretkey
  realm: ttm


# ================================= #
#    Eureka Client Configuration    #
# ================================= #
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: false







sonar:
  projectKey: ms-project
  projectName: Project Microservice
  host:
    url: http://localhost:9000
  login: yourkeyLogin
  sources: src/main/java
  tests: src/test/java
