spring.application.name=ms-document

# Minio server
minio.url=http://localhost:7000
minio.accessKey=minioadmin
minio.secretKey=yassineouben123
minio.bucketName=files

spring.cloud.config.enabled=false
spring.cloud.discovery.enabled=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Max request size (set to 100MB)
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


spring.jpa.database=postgresql
logging.level.root=INFO

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/ttm-document-db
spring.datasource.username=postgres
spring.datasource.password=yassinecoding
spring.datasource.driver-class-name=org.postgresql.Driver



sonar.projectKey=ms-project
sonar.projectName=Project Microservice
sonar.host.url=http://localhost:9000
sonar.login=squ_91b2a5245330a581f09c91c5ec0e6a8cfa508dfa
sonar.sources=src/main/java
sonar.tests=src/test/java



# Minio bucket configuration
server.port=8081
server.address=0.0.0.0
